# Generated by Django 3.0.7 on 2020-07-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='same_address_billing',
            field=models.BooleanField(default=False),
        ),
    ]
