# Generated by Django 3.0.7 on 2020-07-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200715_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
