# Generated by Django 3.0.7 on 2020-07-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200716_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('S', 'Stripe'), ('P', 'Paypal')], max_length=1, null=True),
        ),
    ]
