# Generated by Django 3.0.7 on 2020-07-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200716_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='set_default_billing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='set_default_shipping',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='same_address_billing',
            field=models.BooleanField(default=False),
        ),
    ]
