# Generated by Django 3.0.7 on 2020-08-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200722_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
